# documentation: https://github.com/0dataapp/armadietto-oneclick
# slogan: Node.js remoteStorage server.
# logo: logo.png
# port: 8000

services:
  app:
    image: remotestorage/armadietto-oneclick:coolify@sha256:be18db4ea87dc4574511b529a44e2f010fc0451a1721af35e3fc3d618896549b
    volumes:
      - ${COOLIFY_VOLUME_APP}:/usr/share/armadietto
    environment:
      ALLOW_SIGNUP: ${ALLOW_SIGNUP:-true}
